---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create IAM"

# ------------------------------------------------------------#
#  Resources
# ------------------------------------------------------------#
Resources:
  # ------------------------------------------------------------#
  #  IAM
  # ------------------------------------------------------------#
  CfnRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudformation.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: "/"