---
AWSTemplateFormatVersion: 2010-09-09

Description: playground-cloudformation.yaml

# ------------------------------------------------------------#
#  Parameters
# ------------------------------------------------------------#
Parameters:
  LaunchType:
    Type: String
    Default: EC2
    AllowedValues:
      - Fargate
      - EC2

# ------------------------------------------------------------#
#  Resources
# ------------------------------------------------------------#
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/vpc.yaml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/ecs-cluster.yaml
      Parameters:
        PublicSubnetA: !GetAtt VPC.Outputs.PublicSubnetA
        PublicSubnetC: !GetAtt VPC.Outputs.PublicSubnetC
        PrimaryCidrBlock: !GetAtt VPC.Outputs.PrimaryCidrBlock
        Vpc: !GetAtt VPC.Outputs.Vpc

  ELB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/elb.yaml
      Parameters:
        PublicSubnets: !GetAtt VPC.Outputs.PublicSubnets
        Vpc: !GetAtt VPC.Outputs.Vpc
